import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles";

import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Header, Main, Sidebar, LayoutProvider } from "@/components/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PipeMate",
  description: "PipeMate App Generated by create next app",
};

// * 루트 레이아웃
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 h-full`}
      >
        <SidebarProvider>
          <LayoutProvider>
            <Sidebar />
            <SidebarInset>
              <Header />
              <Main>{children}</Main>
            </SidebarInset>
          </LayoutProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
