import type { Metadata } from 'next';
import '@/styles';

import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Header, MainLayout, Sidebar, LayoutProvider } from '@/components/layout';
import QueryProvider from '@/providers/QueryProvider';
import ToastProvider from '@/providers/ToastProvider';
import { RepositoryProvider } from '@/contexts/RepositoryContext';

export const metadata: Metadata = {
  title: 'PipeMate',
  description: 'PipeMate App Generated by create next app',
};

/**
 * 애플리케이션 루트 레이아웃
 * - 전역 Provider 및 레이아웃을 구성합니다.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="antialiased bg-gray-100 h-full">
        <QueryProvider>
          <RepositoryProvider>
            <SidebarProvider>
              <LayoutProvider>
                <Sidebar />
                <SidebarInset className="relative flex flex-col min-h-screen">
                  <Header />
                  <MainLayout>{children}</MainLayout>
                  <ToastProvider />
                </SidebarInset>
              </LayoutProvider>
            </SidebarProvider>
          </RepositoryProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
